In [1]:
try:
    user_input= int(input("Enter any number: "))
    result=5/user_input
    print("The result of the calculation is: " + str(result))
except Exception as e:
    print(e)

Enter any number: 0
division by zero


In [16]:
subjects = ["Americans" , "Indians"]
verbs = ["play" , "watch"]
objects = ["Baseball" , "Cricket"]

result = [(sub+ " " + verb + " " + obj + ".") for sub in subjects for verb in verbs for obj in objects]
for i in result:
    print(i)

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [22]:
import numpy as np

def vander_matrix(ip, n, increasing=False):
    
    if not increasing:
        matx = np.array([x**(n-1-i) for x in ip for i in range(n)]).reshape(ip.size,n)
    elif increasing:
        matx = np.array([x**i for x in ip for i in range(n)]).reshape(ip.size,n)
    
    return matx

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
matx_dec_order = vander_matrix(inputvector,no_col_opmat,False)
matx_inc_order = vander_matrix(inputvector,no_col_opmat,True)
print("Vander matrix of the input array in decreasing order of powers:\n\n",matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
